# Generated by Django 3.0.3 on 2020-02-27 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='项目名称')),
                ('desc', models.CharField(default='', max_length=200, verbose_name='项目描述')),
                ('last_update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
            },
        ),
    ]
